### ISSUE TITLE
Cant connect via SSL, wrong version

### ISSUE THREAD

**Issue by scrummie02** [polo2ro/imapbox#38]
Using docker image with config with SSL set to true and the correct port get the following:
```
account1/__ALL__ (on imap.host)
Traceback (most recent call last):
  File "/opt/bin/imapbox.py", line 98, in <module>
    main()
  File "/opt/bin/imapbox.py", line 89, in main
    for folder_entry in get_folder_fist(account):
  File "/opt/bin/mailboxresource.py", line 115, in get_folder_fist
    mailbox = imaplib.IMAP4_SSL(account['host'], account['port'])
  File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/local/lib/python3.7/imaplib.py", line 1293, in _create_socket
    server_hostname=self.host)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)
```

**Comment by Maurice-Mueller** [comment]
I just updated the container because I ran into a similar issue. So you can try again and see if it works now.
